name: ğŸ§ª Tests

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.org'
    branches:
      - main

jobs:
  test:
    name: â³ Run tests
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”” Checkout
        uses: actions/checkout@v6
      - name: ğŸ¹ Set up go@1.25.5
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.5'
      - name: ğŸ§ª Run tests
        run: |
          GOCACHE=${GOCACHE:-/tmp/gocache-attesta} go test ./...
        working-directory: ./server
        shell: bash
